/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-tint': '#c8c6c7',
        tertiary: '#00daf8',
        'primary-fixed': '#e5e2e3',
        error: '#ffb4ab',
        'on-primary': '#313031',
        'on-error': '#690005',
        'inverse-on-surface': '#303032',
        'outline-variant': '#46464a',
        'surface-container-low': '#1b1b1d',
        'on-tertiary-fixed': '#001f25',
        'on-surface': '#e4e2e4',
        'error-container': '#93000a',
        'inverse-primary': '#5f5e5f',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#d1bcff',
        'on-tertiary-fixed-variant': '#004e5a',
        'tertiary-fixed-dim': '#00daf8',
        'tertiary-fixed': '#a5eeff',
        'on-secondary-fixed': '#23005b',
        'on-secondary-container': '#ddcdff',
        'on-primary-fixed-variant': '#474647',
        'on-secondary': '#3c0090',
        'primary-container': '#0a0a0b',
        outline: '#919094',
        'inverse-surface': '#e4e2e4',
        'on-background': '#e4e2e4',
        primary: '#c8c6c7',
        'surface-container-highest': '#353437',
        'surface-container-lowest': '#0e0e10',
        'surface-dim': '#131315',
        surface: '#131315',
        'secondary-container': '#7000ff',
        'secondary-fixed': '#e9ddff',
        'surface-variant': '#353437',
        'on-surface-variant': '#c7c6ca',
        'primary-fixed-dim': '#c8c6c7',
        'surface-bright': '#39393b',
        'on-tertiary': '#00363f',
        'on-primary-fixed': '#1c1b1c',
        'surface-container': '#1f1f21',
        'on-secondary-fixed-variant': '#5700c9',
        background: '#131315',
        'on-tertiary-container': '#008599',
        'on-primary-container': '#7a797a',
        'surface-container-high': '#2a2a2c',
        'tertiary-container': '#000c0f',
        secondary: '#d1bcff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '32px',
        unit: '8px',
        'margin-mobile': '24px',
        'container-max': '1440px',
        'margin-desktop': '80px',
      },
      fontFamily: {
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-mono': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Syne', 'sans-serif'],
        'display-lg': ['Syne', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'display-lg-mobile': ['Syne', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['72px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'display-lg-mobile': ['40px', { lineHeight: '1.1', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
